Hivemind support & some polish
RLBot/core pull request #41
Opened 2024-08-06 15:58 UTC by VirxEC

- Hiveminds are now an official feature
 - The first arg to the `RLBotServer` binary is used as the port that `FlatBufferServer` should listen to
   - The port that connects to the game was already dynamic
 - Prevent an error being printed when trying to send a message to a client that unexpectedly disconnected
 - More complex command parsing
   - todo: just run in a shell instead
 - Don't override `SpawnId` if it's not `0`
 - Clear large renders in small chunks
 - Wait for all bots to send a `ReadyMessage` before starting the match
 - Insert default `MutatorSettings` if it's null after getting a `MatchSettings` from a client

2024-08-07 09:06 UTC, NicEastvillage requested changes

2024-08-07 09:06 UTC, NicEastvillage commented on RLBotCS/Main.cs
> +int rlbotSocketsPort = args.Length > 0 ? int.Parse(args[0]) : LaunchManager.RlbotSocketsPort;
Potential parse error here

2024-08-07 09:06 UTC, NicEastvillage commented on RLBotCS/ManagerTools/MatchStarter.cs
> +            }
This part assumes every player config has a unique bot name. In rare cases, this is not true. Only the config path is guaranteed to be unique.

2024-08-07 09:06 UTC, NicEastvillage commented on RLBotCS/ManagerTools/QuickChat.cs
> +                : false
```suggestion
            _chats.First != null && _chats.First.Value.Item1 + ChatDisplaySeconds < gameTime
```

2024-08-07 09:06 UTC, NicEastvillage commented on RLBotCS/ManagerTools/Rendering.cs
> +        }
Was it too expensive to remove all render items at the same time?

2024-08-07 09:06 UTC, NicEastvillage commented on RLBotCS/Server/BridgeHandler.cs
> +                _context.Logger.LogError($"Error while clearning up BridgeHandler: {e}");
```suggestion
                _context.Logger.LogError($"Error while cleaning up BridgeHandler: {e}");
```

2024-08-07 09:06 UTC, NicEastvillage commented on RLBotCS/Server/FlatBuffersSession.cs
> +            case DataType.ReadyMessage when !_connectionEstablished:
Maybe rename ReadyMessage to ConnectionEstablishedMessage?

2024-08-07 20:39 UTC, VirxEC commented on RLBotCS/ManagerTools/Rendering.cs
> +        }
there's a max number of items we can clear in one tick before rocket league starts ignoring them

2024-08-07 20:41 UTC, VirxEC commented on RLBotCS/Server/FlatBuffersSession.cs
> +            case DataType.ReadyMessage when !_connectionEstablished:
maybe `EstablishConnection` would be a better name, we'd probably also want to change the spec for that though

2024-08-07 20:44 UTC, VirxEC commented
everything is crashing and burning today and I just messed up the signing on every commit i've signed so i fixed the ones in this pr at least...

2024-08-07 20:59 UTC, swz-git commented on RLBotCS/Server/FlatBuffersSession.cs
> +            case DataType.ReadyMessage when !_connectionEstablished:
the TCP connection is *technically* already established when the ready message is sent, which would be kinda confusing if it was to be renamed to ConnectionEstablishedMessage or EstablishConnection.

2024-08-07 21:07 UTC, VirxEC commented on RLBotCS/Server/FlatBuffersSession.cs
> +            case DataType.ReadyMessage when !_connectionEstablished:
`ConnectionSettings` maybe?

2024-08-07 21:19 UTC, VirxEC commented on RLBotCS/Main.cs
> +int rlbotSocketsPort = args.Length > 0 ? int.Parse(args[0]) : LaunchManager.RlbotSocketsPort;
It was my thinking that if an invalid port was passed then we probably want to throw an exception and exit - especially since it's right at the start of the program before anything else boots up

2024-08-08 10:48 UTC, NicEastvillage commented on RLBotCS/Main.cs
> +int rlbotSocketsPort = args.Length > 0 ? int.Parse(args[0]) : LaunchManager.RlbotSocketsPort;
Yeah, just give a sensible error message and exit.

2024-08-08 18:56 UTC, NicEastvillage approved these changes

2024-08-08 18:57 UTC, merged