Polish
RLBot/core pull request #48
Opened 2024-10-03 04:52 UTC by VirxEC

- Add name/loadout overrides in the toml parser for match configs
- Update `rl_ball_sym`
- Allow having a non-RLBot version of RL open, opening a second instance of RL that _is_ RLBot
  - Epic only
- Fix bug with `dodge_timeout` in `GameTickPacket`

2024-10-10 22:25 UTC, VirxEC commented
Status: waiting on bridge pr, will be ready after that

2024-10-11 12:50 UTC, NicEastvillage requested changes

2024-10-11 12:50 UTC, NicEastvillage commented on RLBotCS/Server/BridgeMessage.cs
> +            context.Logger.LogError($"Failed to find script with group id {AgentId}");
```suggestion
            context.Logger.LogError($"Failed to find script with agent id {AgentId}");
```

2024-10-11 12:50 UTC, NicEastvillage commented on RLBotCS/Server/BridgeMessage.cs
> +        }
This case should never happen. Better to add `assert(false)` here.

2024-10-11 12:50 UTC, NicEastvillage commented on RLBotCS/Server/BridgeMessage.cs
> +            return;
Ideally, a match controller session would never send a PlayerInfoRequest message. `Assert(false)` instead?

2024-10-11 12:50 UTC, NicEastvillage commented on RLBotCS/Server/BridgeMessage.cs
> +}
Rename to `ClearProcessPlayerReservation`. Does this even have to be a message btw?

2024-10-11 12:50 UTC, NicEastvillage commented on RLBotCS/ManagerTools/ProcPlayerPair.cs
> +}
Not a map. Rename to `PlayerIdPair`

2024-10-11 12:50 UTC, NicEastvillage commented on RLBotCS/ManagerTools/ProcPlayerPair.cs
> +public class ProcPlayerPair
Not a pair. Rename to `AgentReservation` or something similar.

2024-10-12 01:25 UTC, VirxEC commented on RLBotCS/Server/BridgeMessage.cs
> +        }
It can, if the interface sends the wrong agent id to core (for any reason), and I think it would be bad if the server crashed because of that.

2024-10-12 02:30 UTC, VirxEC commented on RLBotCS/Server/BridgeMessage.cs
> +            return;
I moved the check so the request doesn't get sent in the first place

2024-10-12 08:11 UTC, NicEastvillage commented on RLBotCS/Server/BridgeMessage.cs
> +        }
My bad. What happens to the interface/match afterward? Do we just wait for the user to read the error and do something? That might be ok actually. But we could also send an error signal to the interface. I don't know if that is useful.

In any case, `group id` needs to be replaced with `agent id` in the error message.

2024-10-13 12:18 UTC, NicEastvillage approved these changes

2024-10-13 12:19 UTC, merged